events {
    worker_connections 1024;
}

http {
    upstream frontend {
        server nexus-frontend:3000;
    }

    upstream service_operations {
        server service-operations:3005;
    }

    upstream service_analytics {
        server service-analytics:8000;
    }

    server {
        listen 80;

        # Frontend
        location / {
            proxy_pass http://frontend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }

        # API Operations
        location /api/v1/ {
            proxy_pass http://service_operations/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }

        # Socket.io support
        location /socket.io/ {
            proxy_pass http://service_operations/socket.io/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }

        # Analytics
        location /api/v2/graphql {
            proxy_pass http://service_analytics/graphql;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
    }
}
